version: "3.5"
services:
  rostov-nodeserver:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - API_KEY=${API_KEY}
