name: Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]
  workflow_dispatch: # Allows manual run

jobs:
  Avoid_Redundancy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Redundant Deploys
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  # This could be parallelized, but it works quite well as it is
  Deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: "17"
      - name: Install Dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint
      - name: Run Tests
        run: npm run test:coverage
      - name: Upload test:coverage
        run: ./node_modules/.bin/codecov --token="${{secrets.CODECOV_TOKEN}}"
      - name: Copy Dockerfile
        run: npm run docker:cp-root
      - name: Deploy to heroku
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          usedocker: true
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://${{secrets.HEROKU_NAME}}.herokuapp.com/api/health"
          rollbackonhealthcheckfailed: true
          delay: 1.5
          # healthcheck delay in seconds
          # check might occur before the app is ready
          # either wait for healthcheck or remove healthcheck
