name: Pipeline

on:
  push:
    branches: [master]
    paths-ignore: ["**/README.md"]
  pull_request:
    branches: [master]
    paths-ignore: ["**/README.md"]
    types: [opened, synchronize]
  workflow_dispatch: # Allows manual run

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Install:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: "17"
      - name: Install Dependencies
        run: npm ci

  Lint:
    needs: Install
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: "17"
      - name: Install Dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint

  Test:
    runs-on: ubuntu-18.04
    needs: Install
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: "17"
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test:coverage
      - name: Upload test:coverage
        run: ./node_modules/.bin/codecov --token="${{secrets.CODECOV_TOKEN}}"

  Deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs: [Lint, Test]
    runs-on: ubuntu-18.04
    environment:
      name: Production
      url: "https://rostov-nodeserver.herokuapp.com/api-docs"
    steps:
      - uses: actions/checkout@v3
      - name: Copy Dockerfile
        run: npm run docker:cp-root
      - name: Deploy to heroku
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          usedocker: true
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://${{secrets.HEROKU_NAME}}.herokuapp.com/api/health"
          rollbackonhealthcheckfailed: true
          delay: 1.5
          # healthcheck delay in seconds
          # check might occur before the app is ready
          # either wait for healthcheck or remove healthcheck
